version: '3'
services:
  builder:
    build: .
    image: stm32:1.0
    devices:
      - /dev/bus/usb
    volumes:
      - ./demo:/tmp/build
    command: >
      sh -c 'cd /tmp/build && \
        make clean all && \
        (st-util --multi &) && \
        cd /tmp/build && \
        arm-none-eabi-gdb \
          -batch \
          -ex "target extended-remote :4242" \
          -ex "load" \
          -ex "run" \
          outp.elf'
